version: "3"
services:
  node:
    container_name: pms-node
    build: node/
    volumes:
      - ./node:/node
      - /node/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8080:8080"
  db:
    container_name: pms-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/db-data
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./database/scripts:/scripts
volumes:
  db-data:
